app/Http/routes.php
<?php

function eb2bn($str){
	$en = [1,2,3,4,5,6,7,8,9,0];
	$bn = ['১','২','৩','৪','৫','৬','৭','৮','৯','০'];
	return str_replace($en,$bn,$str);
}


Route::group(['middleware' => 'web'], function () {

	Route::get('/', 'HomeController@index');

    // Authentication routes...
	Route::get('login', 'AuthController@showLoginForm');
	Route::post('login', 'AuthController@login');
	Route::get('logout', 'AuthController@logout');

	// Registration routes...
	Route::get('register', 'AuthController@showRegistrationForm');
	Route::post('register', 'AuthController@register');
	Route::get('userlist', 'AuthController@userlist');
	Route::PATCH('profile/{id}', 'AuthController@profile');
	Route::post('password', 'AuthController@password');
	Route::get('userlist/{id}/edit', 'AuthController@useredit');

	//Password Reset routes....
	Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
	Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
	Route::post('password/reset', 'Auth\PasswordController@reset');

    Route::resource('booking', 'BookingController');
    Route::resource('account', 'AccountController');
    Route::get('admin', 'AdminController@index');
    Route::get('admin/{id}', 'AdminController@active');
    Route::get('admin/password/{id}', 'AdminController@password');
    Route::get('admin/admin/{id}', 'AdminController@admin');
    Route::post('item', 'AccountController@itemstore');
    Route::get('bookingsummary', 'BookingsummaryController@index');
    Route::get('accountsummary', 'AccountsummaryController@index');
    Route::get('shop', 'ShopController@index');
	Route::post('shop', 'ShopController@store');
	Route::get('allshop', 'ShopController@allshop');
	Route::post('summary', 'SummaryController@index');
	Route::get('balance/{id}/{balance}/{month}/{year}', 'SummaryController@balance');
	Route::get('useraccounts', 'UseraccountsController@index');
	Route::get('useraccounts/{id}/edit', 'UseraccountsController@edit');
	Route::PATCH('useraccounts/{id}', 'UseraccountsController@update');
	Route::post('monthalyreport', 'MonthalyreportController@index');

});

app/Account.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Account extends Model
{
    protected $fillable = [
        'accountdate', 'description', 'amount',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;
use App\Account;
use Laracasts\Flash\Flash;
use Auth;
use App\Item;
use Carbon\Carbon;

class AccountController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $price = Account::whereMonth('accountdate', '=', date('m'))
            ->where('user_id', Auth::user()->id)
            ->sum('amount');

        $items = Item::lists('item','item');
        $itemname = Item::all();
        $accounts = Account::where('user_id', Auth::user()->id)
            ->orderBy('accountdate', 'desc')
            ->paginate(10);

        return view('accounts.index', [
            'accounts' => $accounts,
            'items' => $items,
            'itemname' => $itemname,
            'price' => $price,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
           'accountdate' => 'required',
            'description' => 'required',
            'amount' => 'required',
        ]);

        $description = implode(", ", $request->description);

        $request->user()->accounts()->create([
            'accountdate' => $request->accountdate,
            'description' => $description,
            'amount' => $request->amount,
        ]);

        Flash::success('আপননার বাজারের নির্দেশনা গ্রহণ করা হয়েছে!');

        return redirect('/account');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $account = Account::findOrfail($id);
        $itemname = Item::all();

        return view('accounts.edit', ['account' => $account, 'itemname' => $itemname]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'accountdate' => 'required',
            'description' => 'required',
            'amount' => 'required',
        ]);

        $account = Account::findorFail($id);
        $account->accountdate = $request->accountdate;
        $account->description = $request->description;
        $account->amount = $request->amount;

        $account->save();

        Flash::success('আপননার বাজারের নির্দেশনা গ্রহণ করা হয়েছে!');
        return redirect('account');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $account = Account::findOrfail($id);
        $account->delete();

        Flash::error('আপনি সফল ভাবে ডিলিট করেছেন!');

        return redirect('/account');

    }

    public function itemstore(Request $request)
    {
        $this->validate($request, [
            'item' => 'required|unique:items',
        ]);

        Item::create([
            'item' => $request->item,
        ]);

        Flash::success('আইটেম সঠিক ভাবে ইনপুট দেওয়া হয়েছে!');

        return redirect()->back();
    }
}

resources/views/accounts/edit.blade.php
@extends('layouts.app')

@section('header')
    <link href="{{ asset('css/select2.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('css/bootstrap-datepicker.css') }}" rel="stylesheet">
@endsection

@section('page-header')
    <h1>
        বাজার <small>সম্পাদন করুন!</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> হোম</a></li>
        <li><a href="{{ url('/booking') }}"><i class="fa fa-coffee"></i> বুকিং</a></li>
        <li><a href="{{ url('/booking') }}"><i class="fa fa-shopping-cart"></i> বাজার</a></li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-danger">
                <div class="box-body">
                    <div class="row">
                        {!! Form::model($account, [
                            'method'=>'PATCH',
                            'route'=>['account.update', $account->id],
                        ]) !!}
                        <div class="panel-body">
                            <div class="col-md-2">
                                {!! Form::text('accountdate', null, ['data-date-format' => 'yyyy/mm/dd', 'data-provide' => 'datepicker', 'class' => 'form-control date', 'placeholder' => 'তারিখ']) !!}
                            </div>
                            <div class="col-md-6">
                                {!! Form::text('description', null, ['class' => 'form-control']) !!}
                            </div>
                            <div class="col-md-2">
                                {!! Form::number('amount', null, ['class' => 'form-control', 'placeholder' => 'টাকা']) !!}
                            </div>

                            <div class="col-md-2">
                                {!! Form::submit('সাবমিট', ['class' => 'btn btn-flat btn-info']) !!}
                                <a class="btn btn-flat btn-primary" href="/account">বাতিল</a>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">বাজারের আইটেম</h3>
                </div>
                <ul class="list-group">
                    @foreach($itemname as $data)
                        <li style="display:inline-block" ><span class="label label-default">{{ $data->item }}</span></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>


@endsection

@section('footer')
    <script src="{{ asset('js/select2.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datepicker.js') }}"></script>
    <script>
        $('.date').datepicker({
            todayHighlight:'TRUE',
            autoclose: 'TRUE',
        });

        $('#description').select2({
            placeholder: "বাজারের আইটেম সিলেট করুন!",
        });
    </script>
@endsection

resources/views/accounts/index.blade.php
@extends('layouts.app')

@section('header')
    <link href="{{ asset('css/select2.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('css/bootstrap-datepicker.css') }}" rel="stylesheet">
@endsection

@section('page-header')
    <h1>
        বাজার <small>কি করেছেন তা লিখুন!</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> হোম</a></li>
        <li><a href="{{ url('/booking') }}"><i class="fa fa-coffee"></i> বুকিং</a></li>
        <li><a href="{{ url('/booking') }}"><i class="fa fa-shopping-cart"></i> বাজার</a></li>
    </ol>
@endsection

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="box box-danger">
                <div class="box-body">
                    <div class="row">
                        {!! Form::open(['route'=>'account.store']) !!}
                        <div class="panel-body">
                            <div class="col-md-2">
                                <input type="text" name="accountdate" data-date-format="yyyy/mm/dd" data-provide="datepicker" class="form-control date" placeholder="তারিখ"/>
                            </div>
                            <div class="col-md-6">
                                {!! Form::select('description[]*', $items, null, ['id' => 'description', 'class' => 'form-control', 'multiple']) !!}
                            </div>
                            <div class="col-md-2">
                                <input type="number" name="amount" class="form-control" placeholder="টাকা"/>
                            </div>

                            <div class="col-md-2">
                                {!! Form::submit('সাবমিট', ['class' => 'btn btn-flat btn-info']) !!}
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">বাজারের হিসাব</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table class="table">
                        <tbody><tr>
                            <th>তারিখ</th>
                            <th>বর্ণনা</th>
                            <th>টাকার পরিমান</th>
                            <th>সম্পাদন</th>
                            <th>ডিলিট</th>
                        </tr>
                        @foreach($accounts as $account)
                            <tr>
                                <td>{{ eb2bn($account->accountdate) }}</td>
                                <td>{{ $account->description }}</td>
                                <td>{{ eb2bn($account->amount) }}</td>
                                <td>
                                    @if($account->created_at->diffInHours(Carbon\Carbon::now()) < 3)
                                        <a href="{{ route('account.edit', $account->id) }}" class="btn btn-flat btn-primary btn-xs">সম্পাদন</a></td>
                                @else
                                    <button type="button" class="btn btn-flat btn-primary btn-xs" disabled="disabled">সম্পাদন</button>
                                @endif
                                <td>
                                    @if($account->created_at->diffInHours(Carbon\Carbon::now()) < 3)
                                        <form action="{{ url('account/'.$account->id) }}" method="POST">
                                            {!! csrf_field() !!}
                                            {!! method_field('DELETE') !!}

                                            <button class="btn btn-flat btn-danger btn-xs">বাতিল</button>
                                        </form>
                                    @else
                                        <button type="button" class="btn btn-flat btn-danger btn-xs" disabled="disabled">বাতিল</button>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody></table>
                </div>
                <!-- /.box-body -->
                <div class="box-footer clearfix">
                    {!! $accounts->render() !!}
                </div>
            </div>


        </div>
        <div class="col-md-4">
            <div class="box box-danger">
                <div class="box-body">
                    <div class="row">
                        {!! Form::open(['action' => 'AccountController@itemstore']) !!}
                        <div class="form-group col-md-8">
                            <input type="text" class="form-control" name="item" placeholder="বাজারের নতুন আইটেমের নাম">
                        </div>
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-flat btn-primary">নতুন আইটেম</button>
                        </div>

                        {!! Form::close() !!}
                    </div>
                </div>
                <!-- /.box-body -->
            </div>

            {{--<h5>এই মাসের হিসাব</h5>--}}
            {{--<ul class="list-group">--}}
                {{--<li class="list-group-item list-group-item-success">--}}
                    {{--<span class="badge"></span>--}}
                    {{--এই মাসে আপনি বাজার করেছেনঃ {{ eb2bn($price) }} টাকা।--}}
                {{--</li>--}}
            {{--</ul>--}}
            {{--<hr />--}}
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">বাজারের আইটেম</h3>
                </div>
                <ul class="list-group">
                    @foreach($itemname as $data)
                        <li style="display:inline-block" ><span class="label label-default">{{ $data->item }}</span></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>

@endsection

@section('footer')
    <script src="{{ asset('js/select2.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datepicker.js') }}"></script>
    <script>
        $('.date').datepicker({
            todayHighlight:'TRUE',
            autoclose: 'TRUE',
        });

        $('#description').select2({
            placeholder: "বাজারের আইটেম সিলেট করুন!",
        });
    </script>
@endsection